from __future__ import annotations

from pathlib import Path
import pandas as pd
import streamlit as st
import plotly.express as px


# -------------------------
# Paths (project structure)
# -------------------------
ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"

CSV_COSTS = DATA_DIR / "cloud_costs.csv"
CSV_SVC = DATA_DIR / "kpi_by_service.csv"
CSV_ENV = DATA_DIR / "kpi_by_env.csv"
CSV_REGION = DATA_DIR / "kpi_by_region.csv"
CSV_INSIGHTS = DATA_DIR / "insights.csv"


def load_csv(path: Path, required: list[str] | None = None) -> pd.DataFrame:
    if not path.exists():
        st.error(f"Missing file: {path}")
        st.stop()
    df = pd.read_csv(path)
    if required:
        missing = set(required) - set(df.columns)
        if missing:
            st.error(f"File {path.name} missing columns: {sorted(missing)}")
            st.stop()
    return df


st.set_page_config(page_title="AWS FinOps Cost Dashboard", layout="wide")

st.title("AWS FinOps Cost Optimization — Executive Dashboard (MVP)")
st.caption("Portfolio project: cost visibility, cost drivers, and waste signals (simulated data).")

# Load data
df_costs = load_csv(CSV_COSTS, required=["date", "service", "region", "environment", "cost"])
df_svc = load_csv(CSV_SVC, required=["service", "cost"])
df_env = load_csv(CSV_ENV, required=["environment", "cost"])
df_region = load_csv(CSV_REGION, required=["region", "cost"])
df_insights = load_csv(CSV_INSIGHTS, required=["insight"])

df_costs["date"] = pd.to_datetime(df_costs["date"], errors="coerce")

# Sidebar filters
st.sidebar.header("Filters (MVP)")
services = ["All"] + sorted(df_costs["service"].unique().tolist())
regions = ["All"] + sorted(df_costs["region"].unique().tolist())
envs = ["All"] + sorted(df_costs["environment"].unique().tolist())

svc_sel = st.sidebar.selectbox("Service", services, index=0)
region_sel = st.sidebar.selectbox("Region", regions, index=0)
env_sel = st.sidebar.selectbox("Environment", envs, index=0)

filtered = df_costs.copy()
if svc_sel != "All":
    filtered = filtered[filtered["service"] == svc_sel]
if region_sel != "All":
    filtered = filtered[filtered["region"] == region_sel]
if env_sel != "All":
    filtered = filtered[filtered["environment"] == env_sel]

total_spend = float(filtered["cost"].sum())
top_service = (
    filtered.groupby("service", as_index=False)["cost"].sum().sort_values("cost", ascending=False).head(1)
)
top_driver_text = "N/A"
if not top_service.empty and total_spend > 0:
    s = top_service.iloc[0]
    top_driver_text = f"{s['service']} (${float(s['cost']):.2f})"

# KPI cards
c1, c2, c3, c4 = st.columns(4)
c1.metric("Total Spend", f"${total_spend:,.2f}")
c2.metric("Top Cost Driver", top_driver_text)
c3.metric("Rows in Dataset", f"{len(filtered):,}")
c4.metric("Regions Covered", f"{filtered['region'].nunique()}")

st.divider()

# Charts
left, right = st.columns(2)

with left:
    st.subheader("Spend by Service")
    svc_chart = filtered.groupby("service", as_index=False)["cost"].sum().sort_values("cost", ascending=False)
    fig = px.bar(svc_chart, x="service", y="cost")
    st.plotly_chart(fig, use_container_width=True)

with right:
    st.subheader("Daily Spend Trend")
    daily = filtered.groupby("date", as_index=False)["cost"].sum().sort_values("date")
    fig2 = px.line(daily, x="date", y="cost", markers=True)
    st.plotly_chart(fig2, use_container_width=True)

# Second row
left2, right2 = st.columns(2)

with left2:
    st.subheader("Spend by Environment")
    env_chart = filtered.groupby("environment", as_index=False)["cost"].sum().sort_values("cost", ascending=False)
    fig3 = px.pie(env_chart, names="environment", values="cost")
    st.plotly_chart(fig3, use_container_width=True)

with right2:
    st.subheader("Spend by Region")
    reg_chart = filtered.groupby("region", as_index=False)["cost"].sum().sort_values("cost", ascending=False)
    fig4 = px.bar(reg_chart, x="region", y="cost")
    st.plotly_chart(fig4, use_container_width=True)

st.divider()

# Insights
st.subheader("Insights / Waste Signals (generated by analysis engine)")
for i, row in enumerate(df_insights["insight"].tolist(), start=1):
    st.write(f"**{i}.** {row}")

with st.expander("Show raw KPI tables"):
    st.write("KPI by service")
    st.dataframe(df_svc, use_container_width=True)
    st.write("KPI by environment")
    st.dataframe(df_env, use_container_width=True)
    st.write("KPI by region")
    st.dataframe(df_region, use_container_width=True)
